const SUPABASE_URL='https://vkakkqsqxlzzmkmjrbnb.supabase.co';const SUPABASE_KEY='sb_publishable_d4fHdeTtEaIRqRjcC1gaBQ_EJkfKRhI';const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const timingNames={1:'1–3 PM',2:'3–5 PM',3:'5–7 PM',4:'7–9 PM',5:'9–11 PM',6:'11 PM–1 AM'};
const $=id=>document.getElementById(id); $('date').value=new Date().toISOString().slice(0,10);
async function owner(){const {data}=await sb.auth.getUser();return data.user}
async function refresh(){const u=await owner();if(!u){$('loginPanel').style.display='block';$('dashboard').style.display='none';return}$('loginPanel').style.display='none';$('dashboard').style.display='block';await loadSettings();await loadTimings();await loadRegs()}
async function loadSettings(){const {data}=await sb.from('admin_settings').select('registrations_enabled').eq('id',1).single();$('toggleAll').textContent=data?.registrations_enabled?'Registrations ON':'Registrations OFF';$('toggleAll').dataset.on=data?.registrations_enabled?'1':'0'}
async function loadTimings(){let html='';for(let id=1;id<=6;id++){const {data}=await sb.rpc('get_timing_capacity',{p_timing_id:id,p_scrim_date:$('date').value});const c=data?.[0]||{};const {data:t}=await sb.from('scrim_timings').select('registrations_paused,is_sold_out').eq('id',id).single();html+=`<div class="contact-card"><b>${timingNames[id]}</b><span class="muted"> ${c.filled_teams??0}/${c.max_teams??18} teams • ${c.remaining_teams??0} left</span><button class="primary" data-pause="${id}" data-value="${t?.registrations_paused?'0':'1'}">${t?.registrations_paused?'Resume':'Pause'}</button><button class="primary" data-sold="${id}" data-value="${t?.is_sold_out?'0':'1'}">${t?.is_sold_out?'Reopen':'Mark Sold Out'}</button></div>`}$('timings').innerHTML=html;document.querySelectorAll('[data-pause]').forEach(b=>b.onclick=async()=>{await sb.rpc('set_timing_paused',{p_timing_id:+b.dataset.pause,p_paused:b.dataset.value==='1'});await loadTimings()});document.querySelectorAll('[data-sold]').forEach(b=>b.onclick=async()=>{await sb.rpc('set_timing_sold_out',{p_timing_id:+b.dataset.sold,p_sold_out:b.dataset.value==='1'});await loadTimings()})}
async function loadRegs(){const {data,error}=await sb.rpc('owner_list_registrations',{p_scrim_date:$('date').value});const rows=data||[];$('regBody').innerHTML=error?`<tr><td colspan="6">${error.message}</td></tr>`:rows.map(r=>`<tr><td>${r.id}</td><td>${r.team_name}</td><td>${timingNames[r.timing_id]||r.timing_id}</td><td>${r.status}</td><td>${r.contact_number}</td><td>${r.status==='cancel_requested'?`<button data-refund="${r.id}">Approve Refund</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="6">No registrations for this date.</td></tr>';document.querySelectorAll('[data-refund]').forEach(b=>b.onclick=async()=>{if(!confirm('Approve refund and release this team slot?'))return;const {error}=await sb.rpc('approve_refund',{p_registration_id:+b.dataset.refund});alert(error?error.message:'Refund approved');await loadTimings();await loadRegs()})}
$('loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});$('loginMsg').textContent=error?error.message:'Signed in';if(!error)refresh()};$('logout').onclick=async()=>{await sb.auth.signOut();refresh()};$('date').onchange=()=>{loadTimings();loadRegs()};$('toggleAll').onclick=async()=>{const on=$('toggleAll').dataset.on==='1';const {error}=await sb.rpc('set_registrations_enabled',{p_enabled:!on});if(error)alert(error.message);await loadSettings()};$('manualForm').onsubmit=async e=>{e.preventDefault();const {data,error}=await sb.rpc('owner_add_registration',{p_team_name:$('mTeam').value,p_contact_number:$('mPhone').value,p_timing_id:+$('mTiming').value,p_scrim_date:$('date').value,p_number_of_slots:+$('mSlots').value,p_price_category:$('mPrice').value});$('manualMsg').textContent=error?error.message:`Added registration #${data}`;if(!error){e.target.reset();$('date').dispatchEvent(new Event('change'))}};$('createMatches').onclick=async()=>{const {data,error}=await sb.rpc('create_matches_for_date',{p_match_date:$('date').value});$('matchMsg').textContent=error?error.message:`Match schedule created/updated. ${data??''}`};sb.auth.onAuthStateChange(()=>setTimeout(refresh,0));refresh();
